Add typescript support with tsconfig
robertdue/mmover pull request #7
Opened 2022-09-22 12:29 UTC by jKelio

- target: ESNext
- active declaration
- active sourceMap
- etc.

2022-09-22 12:33 UTC, jKelio commented
@robertdue ready for review to solve issue #3

Merging with squash?

2022-09-22 12:36 UTC, robertdue commented on main.ts
> +    mouse = getMousePos();
unnecessary to save this global

2022-09-22 13:12 UTC, jKelio commented on main.ts
> +    mouse = getMousePos();
re-review already requested

2022-09-25 06:34 UTC, robertdue commented
Imho Inversify is really unnecessary here. Since there's just a very small amount of classes its way more easy and better readable if we use plain typescript classes.

2022-09-25 06:35 UTC, robertdue requested changes
Imho Inversify is really unnecessary here. Since there's just a very small amount of classes its way more easy and better readable if we use plain typescript classes.

2022-09-27 10:26 UTC, jKelio commented
We are already using plain typescript classes enhanced with the adantages of a lightweight and simple inversion of control.

Due to the official documentation of inversify it has been developed with 4 main goals:

1. Allow JavaScript developers to write code that adheres to the SOLID principles.
2. Facilitate and encourage the adherence to the best OOP and IoC practices.
3. Add as little runtime overhead as possible.
4. Provide a [state of the art development experience](https://github.com/inversify/InversifyJS/blob/master/wiki/ecosystem.md).

Why we shouldn't use the well-known inversion of control pattern?

2022-11-07 10:25 UTC, robertdue approved these changes

2022-11-09 16:00 UTC, merged